# Generated by Django 4.2.6 on 2023-10-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Result Image')),
                ('total', models.IntegerField(default=0)),
                ('car', models.IntegerField(default=0)),
                ('minibus', models.IntegerField(default=0)),
                ('truck', models.IntegerField(default=0)),
                ('trailer', models.IntegerField(default=0)),
                ('motorcycle', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
