# Generated by Django 4.2.6 on 2023-10-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='car',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='minibus',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='motorcycle',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='total',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='truck',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='car_class',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
